services:

  mariadb:
    container_name: mariadb
    env_file:
        - .env
    ports:
        - 3360:3360
    build: ./requirements/mariadb
    image: mariadb:inception
    volumes:
      - db:/var/lib/mysql
    networks:
      - mynetwork
    restart: always

networks:
  mynetwork:
    driver: bridge
