
version: "3"
services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:inception
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - network
    env_file:
      - .env
    ports:
      - 3360:3360
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:inception
    depends_on:
      - mariadb
    restart: always
    env_file:
      - .env
    ports:
      - 9000:9000
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:inception
    depends_on:
      - wordpress
    restart: always
    env_file:
      - .env
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network


volumes:
  mariadb_data:
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/data/mariadb

  wordpress_data:
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/data/wordpress

networks:
  network:
    driver: bridge
