# services:

#   mariadb:
#     container_name: mariadb
#     build: ./requirements/mariadb
#     image: mariadb:inception
#     volumes:
#       - mariadb_data:/var/lib/mysql
#     networks:
#       - network
#     env_file:
#       - .env
#     ports:
#       - 3360:3360
#     restart: always

#   wordpress:
#     container_name: wordpress
#     build: ./requirements/wordpress
#     image: wordpress:inception
#     depends_on:
#       - mariadb
#     restart: always
#     env_file:
#       - .env
#     ports:
#       - 9000:9000
#     volumes:
#       - wordpress_data:/var/www
#     networks:
#       - network
# #volumes
#   volumes:
#     mariadb_data:
#       driver_opts:
#         o: bind
#         type: none
#         device:  $HOME/data/mariadb

#     wordpress_data:
#       driver_opts:
#         o: bind
#         type: none
#         device: $HOME/data/wordpress
# # networks of drivers
#   networks:
#     network:
#       driver: bridge

version: "3"
services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:inception
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - network
    env_file:
      - .env
    ports:
      - 3360:3360
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:inception
    depends_on:
      - mariadb
    restart: always
    env_file:
      - .env
    ports:
      - 9000:9000
    volumes:
      - wordpress_data:/var/www
    networks:
      - network

volumes:
  mariadb_data:
    driver_opts:
      o: bind
      type: none
      device: $HOME/data/mariadb

  wordpress_data:
    driver_opts:
      o: bind
      type: none
      device: $HOME/data/wordpress

networks:
  network:
    driver: bridge